### PR TITLE
Added feature: Transform dynamic form controls to "dynamic" string

### PR DESCRIPTION
**Pull request by lulco**
https://github.com/efabrica-team/phpstan-latte/issues/400

### CODE REVIEW

**Comment by spaze** [comment]
I get a lot of these, and only these, with this branch:

```
 ------ ---------- ----------------------------------------------------------------
  Line   Compiled   Www/Presenters/templates/Trainings/success.latte rendered from
         line       MichalSpacekCz\Www\Presenters\TrainingsPresenter::success
 ------ ---------- ----------------------------------------------------------------
  -1                syntax error, unexpected variable "$values", expecting "{"
 ------ ---------- ----------------------------------------------------------------

 ------ ---------- -----------------------------------------------------------------
  Line   Compiled   Www/Presenters/templates/Trainings/training.latte rendered from
         line       MichalSpacekCz\Www\Presenters\TrainingsPresenter::training
 ------ ---------- -----------------------------------------------------------------
  -1                syntax error, unexpected variable "$values", expecting "{"
 ------ ---------- -----------------------------------------------------------------


 [ERROR] Found 23 errors
```

Guess it's because of a code like this for example in
```
/tmp/phpstan-latte/app/Www/Presenters/templates/Trainings/training.latte.23cf3c308e1217cff0a47695c491d34d.php
```
Notice `$values` in the line with `class Application...`:

```php
class Application_476521386e7f5f980cf9d18a11e420c9_$values extends static(Nette\Forms\Container)
{
    /** @return \Nette\Forms\Controls\BaseControl */
    public function offsetGet($name) : Nette\ComponentModel\IComponent
    {
```

Some of the templates where this happen are quite simple, like for example this one here
https://github.com/spaze/michalspacek.cz/blob/e1362ca993c04810ab847b597f3eff17edf864e3/site/app/Www/Presenters/templates/Trainings/files.latte - no controls, no includes.

**Comment by lulco** [comment]
Ah, I have to ignore some more method calls which returns Form\Container like setTranslator, setRenderer, setDefaults. I’ll prepare fix later

**Comment by lulco** [comment]
@spaze can you try updated version? I made some hotfixes

**Comment by spaze** [comment]
Better, down to just these three:

```
Errors
------

 ------ ---------- --------------------------------------------------------------
  Line   Compiled   Admin/Presenters/templates/Talks/default.latte rendered from
         line       MichalSpacekCz\Admin\Presenters\TalksPresenter::default
 ------ ---------- --------------------------------------------------------------
  -1                syntax error, unexpected variable "$slide", expecting "{"
 ------ ---------- --------------------------------------------------------------

 ------ ---------- -------------------------------------------------------------
  Line   Compiled   Admin/Presenters/templates/Talks/slides.latte rendered from
         line       MichalSpacekCz\Admin\Presenters\TalksPresenter::slides
 ------ ---------- -------------------------------------------------------------
  -1                syntax error, unexpected variable "$slide", expecting "{"
 ------ ---------- -------------------------------------------------------------

 ------ ---------- -----------------------------------------------------------
  Line   Compiled   Admin/Presenters/templates/Talks/talk.latte rendered from
         line       MichalSpacekCz\Admin\Presenters\TalksPresenter::talk
 ------ ---------- -----------------------------------------------------------
  -1                syntax error, unexpected variable "$slide", expecting "{"
 ------ ---------- -----------------------------------------------------------


 [ERROR] Found 3 errors
```

All of them have this or similar:
```php
class Slides_fac2a7d55551999bff07028d779b8514_$slide->slideId extends Nette\Forms\Container
{
    /** @return \Nette\Forms\Controls\BaseControl */
    public function offsetGet($name) : Nette\ComponentModel\IComponent
    {
        /** @var \Nette\Forms\Controls\BaseControl $control */
        $control = parent::offsetGet($name);
        return $control;
    }
}
```

Used here as `$slideIdContainer = $slidesContainer->addContainer($slide->slideId);`:
https://github.com/spaze/michalspacek.cz/blob/e1362ca993c04810ab847b597f3eff17edf864e3/site/app/Form/TalkSlidesFormFactory.php#L43-L43

and here as `{formContainer $slide->slideId}`
https://github.com/spaze/michalspacek.cz/blob/e1362ca993c04810ab847b597f3eff17edf864e3/site/app/Admin/Presenters/templates/Talks/slides.latte#L21-L21

**Comment by lulco** [comment]
Ah name of Container is used as part of class name :( and now it is `$slide->slideId`… OK I have just strip some characters. I’ll add some test cases based on your app :)

**Comment by lulco** [comment]
@spaze now it is fixed. Your first ignored error will disappear. I'm trying to fix/hack the second one

**Comment by lulco** [comment]
OK it will need more time and maybe something from this PR https://github.com/efabrica-team/phpstan-latte/pull/380
I have to reopen it, and recall what I was doing there :D

**Comment by spaze** [comment]
Can confirm that one of those errors have disappeared after upgrading to 0.15.0, thanks 👍

**Comment by lulco** [comment]
Thank you :) you are earlier adopter then me :D

**Pull request merged**
