### PR TITLE
Ignore reporting of unknown @phpstan-latte-* PHPDoc tags

### PR DESCRIPTION
**Pull request by MartinMystikJonas**

### CODE REVIEW

**Review by lulco — APPROVED** [review]

**Comment by lulco** [comment]
This should be in php file ErrorBuilder because errors from config are removable (with ! in config)

**Comment by MartinMystikJonas** [comment]
Thisnis repoeted directly by phpstan as error in php file it does not pass our error builder. Or is there way to influence phostan own errors?

**Comment by lulco** [comment]
So if I have reportUnmatchedErrors turned on this will report issues? It's not good.

**Comment by MartinMystikJonas** [comment]
True we should explicitly turn off reportUnmatched for these errors

**Comment by lulco** [comment]
Just thinking - isn't there some “register” of available phpdoc in phpstan core? It would be great to just register new types to it.

**Comment by MartinMystikJonas** [comment]
It is hardcoded constant https://github.com/phpstan/phpstan-src/blob/73bb9eb0e1f3058f8aba5ee9fb88cad58734c44f/src/Rules/PhpDoc/InvalidPHPStanDocTagRule.php#L22

**Comment by lulco** [comment]
Hmm this is not so unrealistic to change to parameter 🤷

**Comment by MartinMystikJonas** [comment]
Well we can draft PR for it but I am not sure it will be accepted. It is porblem only for annotations starting with `@phpstan`

**Comment by lulco** [comment]
It's phpstan- so we can:
- change our anotation to `phpstanlatte-` (easy win)
- create PR to phpstan
- set report unmatch errors to false for these errors (easy win)

**Comment by MartinMystikJonas** [comment]
I think option 3 is easiest and without BC break so I would go for it.

**Comment by lulco** [comment]
Ok then go for it

**Pull request merged**
