### PR TITLE
LinkProcessor parameters processing fix and fallback to static reflection

### PR DESCRIPTION
**Pull request by MartinMystikJonas**
Relying on native autoload of app classes in PHPStan context can lead to false positive link errors

### CODE REVIEW

**Comment by MartinMystikJonas** [comment]
Found some secondary errors. Need to investigate

**Comment by MartinMystikJonas** [comment]
Found it. There was forgotten throw I for some reson added causing error. And when exception without message is catched it is reported by exception class

**Comment by MartinMystikJonas** [comment]
Found few cases where it still fails

**Comment by MartinMystikJonas** [comment]
All fixed ready to merge

**Review by lulco — APPROVED** [review]

**Pull request merged**
