### PR TITLE
Added phpstan-nette extension to tests

### PR DESCRIPTION
**Pull request by lulco**

### CODE REVIEW

**Comment by lulco** [comment]
@MartinMystikJonas could you please check why multiplier with phpstan-nette extensions not working? It works only with php7.4 (or latte 2.x?), otherwise it thinks that type of multiplier component is mixed

**Comment by lulco** [comment]
With newest phpstan-nette, only three tests failed. With older one there were 7 test failed.

code looks the same, I think it is something with stubs

**Comment by MartinMystikJonas** [comment]
I will check later. But my guess is that it can be related to return type extension https://github.com/phpstan/phpstan-nette/blob/1.1.x/src/Type/Nette/ComponentModelDynamicReturnTypeExtension.php

**Comment by MartinMystikJonas** [comment]
My guess was right. It is bug in phpstan-nette. If createComponent* method is missing it forcibly changes return type to mixed instead of using default return type of getComponent. I will make PR with fix to phpstan-nette.

**Comment by MartinMystikJonas** [comment]
Will be fixed by https://github.com/phpstan/phpstan-nette/pull/119

**Comment by lulco** [comment]
Why it works on php 7.4 and all lowest tests than?

**Comment by MartinMystikJonas** [comment]
Not sure maybe this bug was not present in older versions of phpstan-nette.

**Comment by lulco** [comment]
On php 7.4 it is newest version of extension too 🤷

**Comment by lulco** [comment]
Btw lowest and “non-lowest” tests use the same version of extension. Some of them works, some not.

**Comment by MartinMystikJonas** [comment]
Weird

**Comment by lulco** [comment]
@MartinMystikJonas any news here?

**Comment by MartinMystikJonas** [comment]
No response to my PR in phpstan-nette yet. I will try politely remind.

**Comment by MartinMystikJonas** [comment]
Fix was merged into phpstan-nette. I updated required phpstan-nette version to version with fix and rebased onto main. Should be ready to merge

**Review by lulco — COMMENTED** [review]
Great, we can merge

**Comment by lulco** [comment]
@MartinMystikJonas it looks like it is screwed again in new versions of phpstan-nette extension 😢

**Comment by MartinMystikJonas** [comment]
Ondrej for some reson changed implementation back to forced `mixed`. Not sure why. I asked him in PR comments.

**Comment by MartinMystikJonas** [comment]
It seems it is probably "wont't fix" on Ondřej side. So I think we can either add these arrors to expected errors or ignore them in latte.

**Comment by lulco** [comment]
ok we can ignore them. I was thinking about replacing phpstan-nette's extension in our phpstan-latte but I'm not sure if it would be correct

**Pull request merged**
