### PR TITLE
exit() and die() evaluated as early terminating call

### LINKED ISSUE #291: exit(); is not evaluated as early terminating call
I have Presenter with action like:

```php
public function actionCopy(string $id): void
{
    // do something
    print $id;
    exit();
}
```

There is no template for this action obviously, but I've got error `Cannot resolve latte template for action copy`

### PR DESCRIPTION
**Pull request by lulco**
Resolves https://github.com/efabrica-team/phpstan-latte/issues/291

### CODE REVIEW

**Comment by lulco** [comment]
@MartinMystikJonas I think phpstan count exit and die as early terminating calls

**Comment by MartinMystikJonas** [comment]
We have to check different type of node

**Comment by MartinMystikJonas** [comment]
Fixed but tests needs to be fixed too (changed line numbers and *Sometimes versions should be in expected collected)

**Comment by lulco** [comment]
> Fixed but tests needs to be fixed too (changed line numbers and *Sometimes versions should be in expected collected)

I think I fixed it meantime. There is only sniffer failing now.

**Comment by lulco** [comment]
Thanks for quick fix!

**Pull request merged**
