### PR TITLE
Support for multiline {define} block

### PR DESCRIPTION
**Pull request by MartinMystikJonas**
Currently multile block definition with parameters was not processed correctly - definition and types of parameters was not added

### CODE REVIEW

**Review by lulco — APPROVED** [review]

**Comment by lulco** [comment]
Tests stopped running? :)

**Comment by MartinMystikJonas** [comment]
Workflows was disabled for long inactivity. I reenabled them now

**Comment by MartinMystikJonas** [comment]
It seems something got broken in meantime in PHPstan and 7.4 version. Should I merge this now? Will oyu fix these issue or should I look at it? But I am afraid I will not have time for that soon

**Comment by lulco** [comment]
yeah merge it if you need it

**Pull request merged**
