### PR TITLE
Prevent uninitalized property error when no templates was analysed in current run

### PR DESCRIPTION
**Pull request by MartinMystikJonas**

### CODE REVIEW

**Review by lulco — APPROVED** [review]

**Comment by lulco** [comment]
We can turn on phpstan rule for it.

**Comment by MartinMystikJonas** [comment]
> We can turn on phpstan rule for it.

Not sure what do you mean

**Comment by lulco** [comment]
```neon
parameters:
    checkUninitializedProperties: true
```

**Comment by lulco** [comment]
https://phpstan.org/config-reference#checkuninitializedproperties

**Comment by MartinMystikJonas** [comment]
Oh yes I think we should turn it on.

**Pull request merged**
