### PR TITLE
Collect vars passed as parameter #2 to render methods - object support

### LINKED ISSUE #107: Support object passed to argument #2 or render

### PR DESCRIPTION
**Pull request by MartinMystikJonas**
Resolves #107

### CODE REVIEW

**Comment by lulco** [comment]
I don't know how this exactly works, but in this test cases I would expect an app to throw error about unitialized properties which are accessed in latte. PHPStan should also throw this error

**Comment by MartinMystikJonas** [comment]
We do not have this information available in static anylysis. We are limited by PHPStan capabilities here.

**Comment by lulco** [comment]
So we basically don't test anything for renders with object as 2nd parameter. Template class can say there are fields $a, $b, $c and if developer will not set them, phpstan latte will throw no error.

**Comment by MartinMystikJonas** [comment]
Well recommended use case are constructor promoted properties when it will be handled on PHP level. But when developer passes object with uninitialised properties it cannot be detected by PHPStan.

**Review by lulco — APPROVED** [review]
OK we can merge it now. We will see if there will be some issues

**Pull request merged**
