### PR TITLE
Refactoring of LatteToPhpCompiler

### PR DESCRIPTION
**Pull request by lulco**
Refactoring of LatteToPhpCompiler with the prospect of further changes:
- filters (https://github.com/efabrica-team/phpstan-latte/issues/58)
- engine (https://github.com/efabrica-team/phpstan-latte/issues/143)

### CODE REVIEW

**Comment by MartinMystikJonas** [comment]
I was thinking about similar change. But maybe pass Template to all visitors instead of different setup for each?

**Comment by MartinMystikJonas** [comment]
Maybe remove ActualClassNodeVisitorInterface and make all visitors implement setTemplate(). All visitors would have same setup in DI and all of then would be initialized same way with setTemplate() - and each of them can use what it needs from Template

**Comment by lulco** [comment]
Maybe later, now there is at least AddVarTypesNodeVisitor which don't read variables always from Template. I want to create several interfaces like ActualClassNodeVisitorInteraface for Forms, Components, Filters etc. and each visitor will get only what it needs.

**Comment by MartinMystikJonas** [comment]
ok

**Review by MartinMystikJonas — APPROVED** [review]

**Pull request merged**
