### PR TITLE
Fixed caching problems when storing objects in collector results

### PR DESCRIPTION
**Pull request by MartinMystikJonas**

### CODE REVIEW

**Comment by MartinMystikJonas** [comment]
Alternative solution instead of $forgotX. Add toArray() method (same as jsonSerialioze) and return only this array from Collector? Probably cleaner solution I think.

**Comment by MartinMystikJonas** [comment]
I will update this PR

**Comment by lulco** [comment]
Great, thank you. One more thing: I think, now we don’t need jsonSerialize methods in Collector Value Objects because they are not serialized now (need to check if it is true). I've added them before because of some caching issues

**Comment by MartinMystikJonas** [comment]
Ok i removed them

**Comment by lulco** [comment]
Thank you very much!

**Pull request merged**
