### PR TITLE
Added Error formatter for latte files with context

### LINKED ISSUE #66: Create Error formatter to show from which class/action the template was rendered

### PR DESCRIPTION
**Pull request by lulco**
Resolves https://github.com/efabrica-team/phpstan-latte/issues/66

Output:
```
 ------ ---------------------------------------------------------------------------------------------------------------------- 
  Line   modules/Admin/presenters/templates/Program/channel.latte rendered from modules/Admin/presenters/ProgramPresenter.php  
 ------ ---------------------------------------------------------------------------------------------------------------------- 
  1      Variable $actualChannel in isset() always exists and is not nullable.                                                 
  44     Call to an undefined method Nette\ComponentModel\IComponent::hasErrors().                                             
  51     Call to an undefined method Nette\ComponentModel\IComponent::getErrors().                                             
 ------ ---------------------------------------------------------------------------------------------------------------------- 

 ------ ---------------------------------------------------------------------------------------------------------------------- 
  Line   modules/Admin/presenters/templates/Setting/default.latte rendered from modules/Admin/presenters/SettingPresenter.php  
 ------ ---------------------------------------------------------------------------------------------------------------------- 
  73     Component with name "vp" probably doesn't exist.                                                                      
 ------ ---------------------------------------------------------------------------------------------------------------------- 

 ------ ------------------------------------------------------------------------------------------------------------- 
  Line   modules/Admin/presenters/templates/Show/copy.latte rendered from modules/Admin/presenters/ShowPresenter.php  
 ------ ------------------------------------------------------------------------------------------------------------- 
  23     Call to an undefined method Nette\ComponentModel\IComponent::hasErrors().                                    
  28     Call to an undefined method Nette\ComponentModel\IComponent::hasErrors().                                    
  33     Call to an undefined method Nette\ComponentModel\IComponent::hasErrors().                                    
 ------ ------------------------------------------------------------------------------------------------------------- 
```

### CODE REVIEW

**Comment by MartinMystikJonas** [comment]
Would not it be better to have exact context including render method/action, maybe add it contect description as optional field to Template that is filled by resolver?

**Comment by lulco** [comment]
There is no such information now, I just add actual context to output. We can now play with it. I was thinking to add some "parent" template to included templates etc.

**Comment by MartinMystikJonas** [comment]
Resolver have this information and can pass it to Template.

**Comment by MartinMystikJonas** [comment]
Parent template could be also set as property of Template. It qouls require some improvement but conrext is important i formation so it is good idea to add it.

**Review by MartinMystikJonas — APPROVED** [review]

**Comment by MartinMystikJonas** [comment]
I think it is to merge as it is - we can improve in the future.

**Comment by lulco** [comment]
I've added method / action and included (parent) template info so now it looks like this

```

 ------ ----------------------------------------------------------------------------------------------------------------------- 
  Line   modules/Admin/presenters/templates/Workers/default.latte rendered from App\Admin\Presenters\WorkersPresenter::default  
 ------ ----------------------------------------------------------------------------------------------------------------------- 
  37     Variable $actualClass might not be defined.                                                                            
  40     Variable $actualClass might not be defined.                                                                            
 ------ ----------------------------------------------------------------------------------------------------------------------- 

 ------ -------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------- 
  Line   modules/Admin/presenters/templates/partials/export_modal.latte rendered from App\Admin\Presenters\TrailerPresenter::default included in modules/Admin/presenters/templates/Trailer/default.latte  
 ------ -------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------- 
  1      Variable $yyy might not be defined.                                                                                                                                                               
  11     Component with name "exportForm" probably doesn't exist.                                                                                                                                          
 ------ -------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------- 

```

**Comment by MartinMystikJonas** [comment]
I like it

**Comment by MartinMystikJonas** [comment]
Maybe just add () after function name
```
rendered from App\Admin\Presenters\WorkersPresenter::default()
```

**Pull request merged**
